# -*- coding: utf-8 -*-
"""titanic-cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sbE7ZRe3oFHoXutTVJbGVHxd-Qpm4IJv

# Titanic Data Cleaning and Preprocessing

### Step 1: Import Libraries and Explore Basic Info
"""

# Import Libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Load Dataset
df=pd.read_csv("Titanic-Dataset.csv")
print("First 5 rows:")
print(df.head())

# Basic Info
print("\nDataset Info:")
print(df.info())

# Missing Values
print("\nMissing Values:")
print(df.isnull().sum())

# Data types and basic stats
print("\nData Description:")
print(df.describe(include='all'))

"""### Step 2: Handle Missing Values using Mean/Median/Imputation

---


"""

df['Age']=df['Age'].fillna(df['Age'].median())
df['Embarked']=df['Embarked'].fillna(df['Embarked'].mode()[0])
df = df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'])

print("Missing values handled successfully.")
print(df.isnull().sum())

"""### Step 3: Convert Categorical Features into Numerical using Encoding"""

le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])
df['Embarked'] = le.fit_transform(df['Embarked'])

"""### Step 4: Normalize/Standardize Numerical Features"""

scaler = StandardScaler()

# Select numeric columns
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Do not scale target variable 'Survived' if present
numeric_cols = [col for col in numeric_cols if col != 'Survived']

df[numeric_cols] = scaler.fit_transform(df[numeric_cols])
print("Scaled columns:", numeric_cols)
print("Numerical features standardized.")
print(df.head())

"""### Step 5: Visualize outliers using boxplots and remove them"""

plt.figure(figsize=(15,6))
sns.boxplot(data=df[numeric_cols])
plt.title("Boxplots Before Removing Outliers")
plt.show()

# Remove outliers using IQR method
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df = df[(df[col] >= lower) & (df[col] <= upper)]

print("\nOutliers removed using IQR method.")

plt.figure(figsize=(15,6))
sns.boxplot(data=df[numeric_cols])
plt.title("Boxplots After Removing Outliers")
plt.show()

print(f"Final dataset shape: {df.shape}")

"""### Step 6: Save the Cleaned Dataset"""

df.to_csv("titanic_cleaned.csv", index=False)
print("Cleaned dataset saved as titanic_cleaned.csv")